# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directory: "/ops/cloud/component"
    schedule:
      interval: "daily"
