ci:
    skip: [ggshield, terraform-fmt, terraform-validate, circleci-config-validate]

repos:

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        name: markdown linting

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: update toc

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.13.6
    hooks:
      - id: ggshield
        name: gitguardian scanning

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: trailing whitespace
      - id: end-of-file-fixer
        name: end of file fixer
      - id: check-added-large-files
        name: check added large files
      - id: check-yaml
        name: check yaml
      - id: check-json
        name: check json

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
    - id: circleci-config-validate
      name: circleci validation

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: terraform-fmt
        name: terraform linting
      - id: terraform-validate
        name: terraform validation
