ci:
    skip: [ggshield, pylint]

repos:

  -  repo: https://github.com/psf/black
     rev: 23.7.0
     hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        name: markdown linting

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: update toc

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.0
    hooks:
      - id: ggshield
        name: gitguardian scanning

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: trailing whitespace
      - id: end-of-file-fixer
        name: end of file fixer
      - id: check-added-large-files
        name: check added large files
      - id: check-yaml
        name: check yaml
      - id: check-json
        name: check json
