version: 3

silent: true

includes:
  local: ./ops/taskfile.local.yaml

tasks:
  init:
    desc: initialise local environment
    cmds:
      - task: local:up
      - task: pip:install
      - task: pre-commit:init

  pre-commit:init:
    desc: initialises pre-commit hooks
    silent: true
    cmds:
      - pre-commit autoupdate &>/dev/null &
      - pre-commit install &>/dev/null &

  pip:install:
    desc: installs required pip packages
    silent: true
    cmds:
      - pip install -r .devcontainer/requirements.txt &>/dev/null &
