version: "3.9"

networks:
   local:
     driver: bridge

secrets:
   local:
     file: ./local.env

services:

# partition --------------------------------------------------------------------------

  whoami:
    image: traefik/whoami:v1.7.1
    ports:
      - 8080:80
    networks:
      - local
